### ISSUE TITLE
App crashes after 10 seconds

### ISSUE THREAD

**Issue by artus70** [umer0586/AndroidSMSServer#6]
I have installed AndroidSMSServer as a test. After each start it takes 10 seconds until the app closes automatically, this behaviour can be reliably reproduced.

After several starts my device offered to clear the app cache, but that didn't help.

Android 12 on Samsung Galaxy A52s

**Comment by umer0586** [comment]
While updating the app from version 1.4.0 to 2.0.0 I made several changes in the app's UI. This is surely due to some issue in my UI code so I have to look into the UI code to fix this issue, until then you can use old version (1.4.0) or just start the server within few seconds after starting the app.

**Comment by umer0586** [comment]
I found that this issue is not related to UI code rather its an android's framework restriction for android 8.0 and above which requires services to call `service.startForeground()` within 5 seconds after call to `Context.startForegroundServices()` . This restriction is a serious headache for android developers

There are some methods discussed [here](https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground) which I am looking into to fix the issue

**Comment by artus70** [comment]
Thanks for investigating!

**Comment by umer0586** [comment]
@artus70 I have updated the code please check if error still exists?

**Comment by artus70** [comment]
It runs stable now, great work!
